version: '3.5'
services:
  influxdb:
    image: influxdb:1.8-alpine
    container_name: influxdb
    environment:
      - INFLUXDB_DB=jmeter_results
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    ports:
      - "8086:8086"
    volumes:
      - ./influxdb/data:/var/lib/influxdb
    networks:
      - grafana-influxdb-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    depends_on:
      - influxdb
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - "3000:3000"
    env_file:
      - 'grafana.env'
    links:
      - influxdb
    networks:
      - grafana-influxdb-network

networks:
  grafana-influxdb-network:
    driver: bridge
